# Generated by Django 2.2 on 2019-05-26 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notif',
            old_name='queue',
            new_name='queue1',
        ),
    ]
