# Generated by Django 2.2 on 2019-05-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default=models.EmailField(max_length=254, unique=True, verbose_name='email address'), max_length=255, null=True),
        ),
    ]
