# Generated by Django 2.2 on 2019-06-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190601_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='notif',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
