# Generated by Django 2.2 on 2019-05-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190526_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notif',
            old_name='queue1',
            new_name='queue',
        ),
    ]
