# Generated by Django 2.2 on 2019-06-02 12:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notif_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notif',
            name='is_read',
        ),
        migrations.AddField(
            model_name='notif',
            name='is_read',
            field=models.ManyToManyField(related_name='notif_is_read', to=settings.AUTH_USER_MODEL),
        ),
    ]
