# Generated by Django 2.2.1 on 2019-06-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190602_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_get_notif_email',
            field=models.BooleanField(default=False),
        ),
    ]
