# Generated by Django 2.2 on 2019-05-26 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notif_is_show_notif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notif',
            name='message',
        ),
    ]
