# Generated by Django 2.2 on 2019-05-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_notif_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notif',
            name='is_owner',
        ),
        migrations.RemoveField(
            model_name='notif',
            name='is_queue',
        ),
        migrations.RemoveField(
            model_name='notif',
            name='is_show_notif',
        ),
        migrations.RemoveField(
            model_name='notif',
            name='is_signature',
        ),
        migrations.RemoveField(
            model_name='notif',
            name='is_signature_request',
        ),
        migrations.AddField(
            model_name='notif',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
