# Generated by Django 2.2 on 2019-05-12 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notif',
            name='doc',
        ),
    ]
