# Generated by Django 2.2.1 on 2019-06-11 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190608_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='notif',
            name='initiator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notif2', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
