# Generated by Django 2.2.1 on 2019-06-11 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_notif_initiator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notif',
            name='initiator',
        ),
    ]
