# Generated by Django 2.2.1 on 2019-06-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_notif_initiator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_get_notif_expired_email',
            field=models.BooleanField(default=False),
        ),
    ]
