# Generated by Django 2.2 on 2019-05-18 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190518_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif', to='docs.Doc'),
        ),
        migrations.AlterField(
            model_name='notif',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif', to=settings.AUTH_USER_MODEL),
        ),
    ]
