# Generated by Django 2.2.1 on 2019-06-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_is_get_notif_expired_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='notif',
            name='dateExpire',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
