# Generated by Django 2.2 on 2019-05-24 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_notif_issignature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notif',
            old_name='isSignature',
            new_name='is_signature',
        ),
    ]
