# Generated by Django 2.2 on 2019-05-24 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_auto_20190524_1802'),
        ('users', '0012_auto_20190524_1802'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notif',
            unique_together={('user', 'doc', 'owner')},
        ),
    ]
