# Generated by Django 2.2.1 on 2019-06-13 21:31

from django.db import migrations, models
import storages.backends.ftp


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_notif_is_notif_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.ftp.FTPStorage(), upload_to='avatars'),
        ),
    ]
