# Generated by Django 2.2.1 on 2019-06-14 21:56

from django.db import migrations, models
import ftp


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190614_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=ftp.FTPStorage(), upload_to='./avatars/'),
        ),
    ]
