# Generated by Django 2.2.1 on 2019-06-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0012_block'),
        ('users', '0014_auto_20190615_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block',
            field=models.ManyToManyField(related_name='user_block', to='docs.Block'),
        ),
    ]
