# Generated by Django 2.2.1 on 2019-06-15 18:07

from django.db import migrations, models
import ftp


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=ftp.FTPStorage(), upload_to='avatars'),
        ),
    ]
