# Generated by Django 2.2.1 on 2019-06-16 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20190615_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notif',
            name='date_expire',
        ),
        migrations.RemoveField(
            model_name='notif',
            name='is_notif_expire',
        ),
    ]
