# Generated by Django 2.2.1 on 2019-06-17 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20190616_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='block',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_get_block',
        ),
    ]
