# Generated by Django 2.2 on 2019-05-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
