# Generated by Django 2.2.1 on 2019-06-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20190607_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='signature',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
