# Generated by Django 2.2 on 2019-05-18 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20190512_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='owner',
        ),
    ]
