# Generated by Django 2.2.1 on 2019-06-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_auto_20190608_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
