# Generated by Django 2.2 on 2019-05-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_remove_doc_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
