# Generated by Django 2.2 on 2019-05-31 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_filecabinet'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='fileCabinet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doc', to='docs.FileCabinet'),
            preserve_default=False,
        ),
    ]
