# Generated by Django 2.2 on 2019-05-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_doc_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='preview',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
