# Generated by Django 2.2 on 2019-05-31 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_doc_filecabinet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='fileCabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc', to='docs.FileCabinet'),
        ),
    ]
