# Generated by Django 2.2.1 on 2019-06-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_auto_20190608_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='cancel_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='cancel_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='doc',
            name='signature',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
