# Generated by Django 2.2 on 2019-05-31 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_auto_20190531_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='preview',
        ),
    ]
