# Generated by Django 2.2 on 2019-05-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_doc_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
