# Generated by Django 2.2.1 on 2019-06-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_auto_20190609_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='signature_end',
            field=models.BooleanField(default=False),
        ),
    ]
