# Generated by Django 2.2.1 on 2019-06-13 21:31

from django.db import migrations, models
import storages.backends.ftp


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_auto_20190613_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='cancel_file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.ftp.FTPStorage(), upload_to='cancel_docs'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.ftp.FTPStorage(), upload_to='docs'),
        ),
    ]
