# Generated by Django 2.2 on 2019-06-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_auto_20190531_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
