# Generated by Django 2.2.1 on 2019-06-14 21:56

from django.db import migrations, models
import ftp


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_auto_20190614_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='cancel_file',
            field=models.FileField(blank=True, null=True, storage=ftp.FTPStorage(), upload_to='./cancel_docs/'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='file',
            field=models.FileField(blank=True, null=True, storage=ftp.FTPStorage(), upload_to='./docs/'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='signature',
            field=models.FileField(blank=True, null=True, storage=ftp.FTPStorage(), upload_to='./sign/'),
        ),
    ]
