# Generated by Django 2.2.1 on 2019-06-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_auto_20190615_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='signature_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
