# Generated by Django 2.2.1 on 2019-06-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0011_auto_20190615_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=500, null=True)),
                ('hash', models.CharField(blank=True, max_length=500, null=True)),
                ('previous_hash', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
