# Generated by Django 2.2.1 on 2019-06-17 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0014_auto_20190616_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='hash',
            new_name='hash_field',
        ),
    ]
