# Generated by Django 2.2.1 on 2019-06-17 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0016_auto_20190617_0316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='hash_field',
            new_name='hash',
        ),
    ]
