export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_TOKEN = 'AUTH_TOKEN'
export const AUTH_SIGNUP = 'AUTH_SIGNUP'
export const AUTH_REQUEST = 'AUTH_REQUEST'

export const USER_REQUEST = 'USER_REQUEST'
export const USERS_REQUEST = 'USERS_REQUEST'
export const USER_SUCCESS = 'USER_SUCCESS'
// export const USER_NOTIF_REQUEST = 'USER_NOTIF_REQUEST'
export const USER_ERROR = 'USER_ERROR'
export const USER_UPDATE = 'USER_UPDATE'
export const USER_CONFIRM_UPDATE_PASSWORD = 'USER_CONFIRM_UPDATE_PASSWORD'
export const USER_CHANGE_PASSWORD = 'USER_CHANGE_PASSWORD'
export const USER_UPDATE_STAFF = 'USER_UPDATE_STAFF'
export const USER_UPDATE_IMAGE = 'USER_UPDATE_IMAGE'
export const USER_NOTIF_R = 'USER_NOTIF_R'

export const DOCS_REQUEST = 'DOCS_REQUEST'
export const DOC_SUCCESS = 'DOC_SUCCESS'
export const DOC_ERROR = 'DOC_ERROR'
export const DOC_UPLOAD = 'DOC_UPLOAD'
export const DOC_UPLOAD_SUCCESS = 'DOC_UPLOAD_SUCCESS'
export const DOC_REQUEST = 'DOC_REQUEST'
export const DOC_SIGNATURE = 'DOC_SIGNATURE'
export const DOC_FOLDER_PAGE = 'DOC_FOLDER_PAGE'
export const DOC_FOLDER_PAGE_PROFILE = 'DOC_FOLDER_PAGE_PROFILE'
export const DOCS_SUCCESS = 'DOCS_SUCCESS'
export const DOC_REQUEST_SUCCESS = 'DOC_REQUEST_SUCCESS'

export const path = 'http://localhost:8000'
// export const path = 'https://edms-mtuci.herokuapp.com'