# Generated by Django 2.1.4 on 2019-03-06 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190303_2228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippet',
            new_name='User',
        ),
    ]
